---
- name: Configure nfs-client
  hosts: nfsc
  become: true
  gather_facts: false

  tasks:

    - name: Ensure nfs-common is installed
      ansible.builtin.package:
        name: nfs-common
        update_cache: true

    - name: Create a directory
      ansible.builtin.file:
        path: /mnt/nfs
        mode: '0755'
        owner: root
        group: root
        state: directory

    - name: 'Mount 192.168.50.10:/srv/share/ in /mnt/nfs'
      ansible.posix.mount:
        src: '192.168.50.10:/srv/share/'
        path: /mnt/nfs
        fstype: nfs
        state: mounted
...